server:
  port : 9999
zuul:
  routes:
    offer:
      path: /offer/**
      url: http://34.228.12.159:1001/api/v1
    shoe:
      path: /shoe/**
      url: http://34.228.12.159:1002/api/v1
    wishlist:
      path: /wishlist/**
      url: http://34.228.12.159:1003
    cart:
      path: /cart/**
      url: http://34.228.12.159:1004/api/v1
