apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: myspace
  labels:
    app: cart
spec:
  selector:
    matchLabels:
      app: cart
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  cart
    spec:
      containers:
      - name:  shoe
        image:  tarunk0/cart:v1
        ports:
        - containerPort:  1004
          name:  shoe

---

apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: myspace
spec:
  selector:
    app: cart
  type: ClusterIP
  ports:
  - name: cart
    protocol: TCP
    port: 1004
    targetPort: 1004
    